# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [7]:
print("number of axes", A.ndim)
print("shape:", A.shape)
print("size:", A.size)
print("Datatype:", A.dtype)

number of axes 2
shape: (3, 5)
size: 15
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [9]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [17]:
Elementwise_subtraction = B-C
Elementwise_multiplication = B*C
Matrix_multiplication = B@C

print("subtraction:\n", Elementwise_subtraction)
print()
print("multiplication:\n", Elementwise_multiplication)
print()
print("matrix multiplication:\n", Matrix_multiplication)


subtraction:
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

multiplication:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

matrix multiplication:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [18]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
Exponentiate_elementwise = np.exp(B)   # detta är e^x för varje element i B
min_value = np.min(B)
minvalue_row = np.min(B, axis=1)
minvalue_col = np.min(B, axis=0)
index_min= np.argmin(B)
index_min_row = np.argmin(B, axis=1)
Sum = np.sum(B)
Mean_column = np.mean(B, axis=0)
Median_column = np.median(B, axis=0)

print("e^x i varje element:\n", Exponentiate_elementwise)
print()
print("minsta värdet i hela B: \n", min_value)
print()
print("minsta värdet i varje rad: \n", minvalue_row)
print()
print("minsta värdet i varje kolumn: \n", minvalue_col)
print()
print("index för minsta värdet: \n", index_min)
print()
print("index för minsta värdet i varje rad: \n", index_min_row)
print()
print("Summan av alla element: \n", Sum)
print()
print("Medelvärdet av varje kolumn: \n", Mean_column)
print()
print("Medianvärdet (mitten) av varje kolumn: \n", Median_column)


e^x i varje element:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

minsta värdet i hela B: 
 1

minsta värdet i varje rad: 
 [1 4 7]

minsta värdet i varje kolumn: 
 [1 2 3]

index för minsta värdet: 
 0

index för minsta värdet i varje rad: 
 [0 0 0]

Summan av alla element: 
 45

Medelvärdet av varje kolumn: 
 [4. 5. 6.]

Medianvärdet (mitten) av varje kolumn: 
 [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [22]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [23]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

### `[[ 1  2  3  4  5]` detta är index 0
### `[ 6  7  8  9 10]`detta är index 1  
### `[11 12 13 14 15]]` detta är index 2
### `A[1]`  retunerar index 1 vilket är rad 2
det betyder att  du får ut alla element i den dimensionen som du inte har angett något index för

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [24]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [29]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [30]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# Svar: 
`a = np.arrage(30)` : Skapar numpy-array som innehåller värden från 0 till 29

`b = a.reshape((2, 3, -1))` = Reshapar a till en 3D-array, `2`: två "Grupper", `3`: varje grupp har 3 rader `-1`: automatik uträkning av hur många element varje rad ska ha (för att uppnå 30)

`print(a)`  = skriver ut värderna 0-29 (30)

`print(b)` = skriver ut arrayen b med 2 grupper där första gruppen (0-14) och andra (15-29) 

## Att b har 3 axlar:

`axis 0 =`: antal "grupper" , 2 i detta fall 

`axis 1 =`: raderna i varje grupp , 3 i detta fall

`axis 2 =`: kolumner i varje rad, (här har varje rad 5 element)

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [32]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [33]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [34]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments

(validate that the input are of the type numpy.ndarray by using the isinstance function), 

a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices 
(validate that the third argument is either 'add' or 'multiply'). 

When doing matrix addition, validate that the matrices have the same size.

When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [152]:
import numpy as np

def add_mult_matrices(A, B, addmult):
    A = np.array(A) #gör om A till en numpy array
    B = np.array(B)     

    if not isinstance(A, np.ndarray): #isistance kollar om A är en numpy array
        return " A is not a numpy array" 
    if not isinstance(B, np.ndarray): 
        return " B is not a numpy array"
    
    if addmult not in ['add', 'multiply']:
        return "choose add or multiply"
    
    if addmult == "add":
        if A.shape != B.shape:
            return "Most have the same size for addition"
        else:
          return (A + B)
        
    elif addmult == "multiply":
        if A.shape[1] != B.shape[0]:
            return "The number of columns in A must be equal to the number of rows in B"
        else:
            return (A @ B)
        
Ex_A = [[1, 2], [3, 4]]
Ex_B = [[5, 6], [7, 8]]
c = add_mult_matrices(Ex_A, Ex_B, "add")
print(c)

[[ 6  8]
 [10 12]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [107]:
## UPPGIFT 10.1.1

import numpy as np


x = np.array([[4,3]])

dimenson_x = x.shape #kollar dimensionen på x
print("(A) Dimension:", dimenson_x) #skriver ut dimensionen på x
print()

calculate_5x = 5*x #multiplicerar x med 5
print("(B) 5x = ", calculate_5x) #skriver ut 5*x
print()

calculate_3x = 3*x #multiplicerar x med 3
print("(C) 3x = ", calculate_3x) #skriver ut 3*x
print()

calculate_5x_plus_3x = 5*x + 3*x #adderar 5*x och 3*x
print("(D) 5x + 3x = ", calculate_5x_plus_3x) #skriver ut 5*x + 3*x
print()

calculate_8x = 8*x #multiplicerar x med 8
print("(E) 8x = ", calculate_8x) #skriver ut 8*x
print()

calculate_4x_minus_x = 4*x - x #subtraherar x från 4*x
print("(F) 4x - x =", calculate_4x_minus_x) #skriver ut 4*x - x
print()

transponera_x = x.T #transponerar x
dimension_tr = transponera_x.shape #kollar dimensionen på transponerade x
print("(G) x^T = \n", transponera_x, "\n New dimension =", dimension_tr) #skriver ut transponerade x
print()

if x.shape == transponera_x.shape:
    definierat = x + transponera_x 
    print("(H) x och x^T har samma dimension") 
else: 
    print("(H) x och x^T har inte samma dimension")
print()

normen_x = np.linalg.norm(x) #räknar ut normen av x, linlang står för 
print("(I) Normen av x = ", normen_x) #skriver ut normen av x    

(A) Dimension: (1, 2)

(B) 5x =  [[20 15]]

(C) 3x =  [[12  9]]

(D) 5x + 3x =  [[32 24]]

(E) 8x =  [[32 24]]

(F) 4x - x = [[12  9]]

(G) x^T = 
 [[4]
 [3]] 
 New dimension = (2, 1)

(H) x och x^T har inte samma dimension

(I) Normen av x =  5.0


In [109]:
## UPPGIFT 10.1.2
v = np.array([[3,7,0,11]])
dimension = v.shape 
print("(A) Dimension:", dimension)
print()

calculate_2v = 2*v
print("(B) 2v = ", calculate_2v)
print()

calculate5v_2v = 5*v + 2*v
print("(C) 5v + 2v = ", calculate5v_2v)
print()

calculate4v_2v = 4*v - 2*v
print("(D) 4v - 2v = ", calculate4v_2v)
print()

transponera_v = v.T
dimension_tr = transponera_v.shape
print("(E) v^T = \n", transponera_v, "\n New dimension =", dimension_tr) 
print()

normen_v = np.linalg.norm(v)
print("(F) Normen av v = ", normen_v)


(A) Dimension: (1, 4)

(B) 2v =  [[ 6 14  0 22]]

(C) 5v + 2v =  [[21 49  0 77]]

(D) 4v - 2v =  [[ 6 14  0 22]]

(E) v^T = 
 [[ 3]
 [ 7]
 [ 0]
 [11]] 
 New dimension = (4, 1)

(F) Normen av v =  13.379088160259652


In [115]:
## UPPGIFT 10.1.3
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

normen_v1 = np.linalg.norm(v1)
print("(A) Normen av v1 = ", normen_v1)


normen_v1_v2 = np.linalg.norm(v1 - v2)
print("(B) Normen av v1-v2 = ", normen_v1_v2) 

(A) Normen av v1 =  7.14142842854285
(B) Normen av v1-v2 =  4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [137]:
## UPPGIFT 10.2.1

A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

calculate_2A = 2*A
print("(A) 2A = \n", calculate_2A)
print()

calculate_B_2A = B - 2*A
print("(B) B - 2A = \n", calculate_B_2A)
print()

if C.shape == E.shape:
    calculate_3C_2E = 3 * C - 2 * E
    print("(C) 3C - 2E = \n", calculate_3C_2E)
else:
    print("(C) 3C - 2E = Ej definierad på grund av olika dimensioner")
print()

calculate_2D_3C = 2*D - 3*C
print("(D) 2D - 3C = \n", calculate_2D_3C)
print()

calculate_Dt_2D = D.T + 2*D
print("(E) D^T + 2D = \n", calculate_Dt_2D)
print()

calculate_2Ct_2Dt = 2*C.T - 2*D.T
print("(F) 2C^T - 2D^T = \n", calculate_2Ct_2Dt)
print()

try:
    calculate_At_B = A.T - B 
    print("(G) A^T - B = \n", calculate_At_B)
except ValueError:
    print("(G) A^T - B = Ej definierat")
print()

try:
    calculate_AC = A @ C
    print("(H) AC = \n", calculate_AC)
except ValueError:
    print("(H) AC = Ej definierat eftersom antalet kolumner i A inte är lika med antalet rader i C")
print()

calculate_CD = C @ D
print("(I) CD = \n", calculate_CD)
print()

calculate_CB = C @ B
print("(J) CB = \n", calculate_CB)
print()

calculate_CI = C @ I
print("(K) CI= \n", calculate_CI)
print()

calculate_ABt = A @ B.T
print("(L) AB^T = \n", calculate_ABt)
print()

(A) 2A = 
 [[ 4  2 -2]
 [ 2 -2  2]]

(B) B - 2A = 
 [[ 0 -4  3]
 [ 0 -2 -4]]

(C) 3C - 2E = Ej definierad på grund av olika dimensioner

(D) 2D - 3C = 
 [[3 2]
 [2 3]]

(E) D^T + 2D = 
 [[ 9 12]
 [12  9]]

(F) 2C^T - 2D^T = 
 [[-4 -4]
 [-4 -4]]

(G) A^T - B = Ej definierat

(H) AC = Ej definierat eftersom antalet kolumner i A inte är lika med antalet rader i C

(I) CD = 
 [[11 10]
 [10 11]]

(J) CB = 
 [[  8 -10  -3]
 [ 10  -8   0]]

(K) CI= 
 [[1 2]
 [2 1]]

(L) AB^T = 
 [[5 2]
 [7 4]]



In [142]:
# UPPGIFT 10.2.2
A = np.array([[2,3,4], [5,4,1]])

Calculate_AAt = A @ A.T
print("A*A^T =\n ",Calculate_AAt)

A*A^T =
  [[29 26]
 [26 42]]


In [146]:
#UPPGIFT 10.2.3
A = np.array([[1,2], [2,4]])
B = np.array([[2,1], [1,3]])
C = np.array([[4,3], [0,2]])

Calculate_AB = A @ B
print("A*B =\n ",Calculate_AB)
print()

Calculate_AC= A @ C
print("A*C =\n ",Calculate_AC)
print()

if np.array_equal (Calculate_AB, Calculate_AC):
    print("AB = AC")
else:
    print("AB != AC")
print() 

if not np.array_equal (B , C):
    print("B is not equal to C")
else:
    print("B = C")

A*B =
  [[ 4  7]
 [ 8 14]]

A*C =
  [[ 4  7]
 [ 8 14]]

AB = AC

B is not equal to C


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

View: Delar samma data som originalarrayen. Om man ändrar elementi viewen ändras samma element i original arrayen 

Copy: Har egen separat kopia av datan. Därav ändras inte originalarrayen

In [147]:
v1 = np.arange(4) #skapar en array med värden 0-3
v2 = v1[-2:] #väljer de två sista elementen i v1 och sparar i v2
print(v1) #skriver ut v1
print(v2) #skriver ut v2


[0 1 2 3]
[2 3]


In [148]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base) #skriver ut v1s base
print(v2.base)  #skriver ut v2s base

None
[0 1 2 3]


In [149]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123    #ändrar det sista elementet i v2 till 123
print(v1)    #skriver ut v1 
print(v2)   #skriver ut v2

[  0   1   2 123]
[  2 123]
